#!/bin/bash

python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=0;
#python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=1;
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=2;
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=3;
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=4;
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=5;
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=6;
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=7;
#python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=8;  
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=9;
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=10;
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=11;
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=12;
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=13;
#python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=14;  
#python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=15;
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=16;
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=17;
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=18;
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=19;
#python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=20;  
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=21;
#python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=22;  
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=23;
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=24;
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=25;
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=26;
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=27;
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=28;
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=29;
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=30;
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=31;
#python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=32;  
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=33;
python3 prio.py --rwlong=1 --numjobs=5 --iocost3=1 --configpoint=34;

#python3 prio.py --rwlong_joined=1 --numjobs=5 --iocost2=1 --configpoint=4;
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iocost2=1 --configpoint=6;
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iocost2=1 --configpoint=11;
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iocost2=1 --configpoint=13;
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iocost2=1 --configpoint=18;  
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iocost2=1 --configpoint=20;  
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iocost2=1 --configpoint=25;  
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iocost2=1 --configpoint=27;  
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iocost2=1 --configpoint=32;  
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iocost2=1 --configpoint=34;  

python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=0;  
python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=1;  
#python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=2;  
#python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=3;
#python3 prio.py --rwlong=1 --numjobs=5 --iomax=5 --configpoint=4;
python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=5;  
python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=6;  
python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=7;  
python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=8;  
python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=9;  
python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=10;  
python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=11;  
python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=12;  
python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=13;  
python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=14;  
python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=15;  
python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=16;  
python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=17;  
python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=18;  
python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=19;  
python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=20;  
python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=21;  
python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=22;  
python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=23;  
python3 prio.py --rwlong=1 --numjobs=5 --iomax=1 --configpoint=24;  


#python3 prio.py --rwlong=1 --numjobs=5 --iolat=1 --configpoint=2;  
#python3 prio.py --rwlong=1 --numjobs=5 --iolat=1 --configpoint=3;
#python3 prio.py --rwlong=1 --numjobs=5 --iolat=5 --configpoint=4;

#python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=0;  
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=1;
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=2;  
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=3;
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=4;
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=5;
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=6;
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=7;  
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=8;
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=9;
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=10;
python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=11;
python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=12;
python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=13;
python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=14;
python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=15;
python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=16;
python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=17;
python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=18;
python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=19;
python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=20;
python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=21;
python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=22;
python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=23;
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iomax=1 --configpoint=24;  

#python3 prio.py --rwlong_joined=1 --numjobs=5 --iolat=1 --configpoint=0;  
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iolat=1 --configpoint=1;
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iolat=1 --configpoint=2;  
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iolat=1 --configpoint=3;
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iolat=1 --configpoint=4;
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iolat=1 --configpoint=5;
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iolat=1 --configpoint=30;  
#python3 prio.py --rwlong_joined=1 --numjobs=5 --iolat=1 --configpoint=44;  

#python3 prio.py --iocost4=1 --tapps_joined=1 --rq_joined=1 --access_joined=1 --numjobs=5
#python3 prio.py --iocost4=1 --access_joined=1 --numjobs=5
#python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=0 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=1 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=2 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=3 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=4 --numjobs=5
#python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=5 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=6 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=7 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=8 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=9 --numjobs=5
#python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=10 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=11 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=12 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=13 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=14 --numjobs=5
#python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=15 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=16 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=17 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=18 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=19 --numjobs=5
#python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=20 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=21 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=22 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=23 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=24 --numjobs=5
#python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=25 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=26 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=27 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=28 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=29 --numjobs=5
#python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=30 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=31 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=32 --numjobs=5
#python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=33 --numjobs=5
python3 prio.py --iocost4=1 --rwlong_joined=1 --configpoint=34 --numjobs=5
